version: "3.9"
services:
  db:
    image: postgres
    networks: 
      zabbix-network:
        ipv4_address: 10.0.0.1
    container_name: postgres-server
    restart: always
    env_file:
      - ./env/db.env
    volumes:
      - nfs:/var/lib/postgresql/data/
  srv:
    image: zabbix/zabbix-server-pgsql:alpine-5.2-latest
    networks: 
      zabbix-network:
        ipv4_address: 10.0.0.2
    container_name: zabbix-server-pgsql
    restart: always
    env_file:
      - ./env/srv.env
  web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-5.2-latest
    networks: 
      zabbix-network:
        ipv4_address: 10.0.0.3
    container_name: zabbix-web-nginx-pgsql
    restart: always
    env_file:
      - ./env/web.env
    ports: 
      - 443:8443
      - 80:8080

volumes:
  nfs:
    driver_opts:
      type: nfs
      o:  nfsvers=3,addr=10.100.0.1,rw,nolock,soft
      device: ":/vol/vol_zabbix00/data"

networks:
  zabbix-network:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
          gateway: "10.0.0.254"